name: CI

on:
  pull_request:
    branches: [ master ]

  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Run weekly to detect compiler or dependency regressions.
  schedule:
    - cron: "0 0 * * 0"

jobs:
  test-on-nightly:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: diku-dk/install-futhark@v1.1.0
      with:
        version: 'nightly'

    - run: futhark pkg sync

    - run: futhark test --pass-compiler-option=--Werror lib

    - run: futhark pkg upgrade

    - run: futhark pkg sync

    - run: futhark test --pass-compiler-option=--Werror lib
